### PR TITLE
Add Docker image

### PR DESCRIPTION
**Pull request by yusufsheiqh**
## Context

- Add `Dockerfile` and `docker-compose.yml` files for local development via Docker using multistage builds.
- Update README with instructions for Docker Compose.
- Expose required ports:
  - to allow use of local database clients (DataGrip, Postico, etc.) to connect to the Postgres database running within the container
  - to be able to access [localhost:8080](http://localhost:8080) (0.0.0.0 can also be used in-place of localhost)

For usage...

```bash
echo "test test test" | curl -F "file=@-" localhost:8080
```

### CODE REVIEW

**Comment by yusufsheiqh** [comment]
Hey @vaaleyard - could you take a look at this please? It would be great to get this merged sooner than later.

**Comment by vaaleyard** [comment]
I'm sorry for the late response @yusufsheiqh, i will approve it. And I really appreciate you by taking a time to develop this PR. Thanks.

**Comment by yusufsheiqh** [comment]
No worries at all! Thank you in advance, @vaaleyard. 🚀

**Comment by yusufsheiqh** [comment]
Hey @vaaleyard, gentle reminder to get this approved and merged - it has been over a month since our previous comments.

**Comment by vaaleyard** [comment]
Could you make the changes I suggested? Then, I can merge it.

**Comment by yusufsheiqh** [comment]
Hey @vaaleyard - I cannot see your suggestions anywhere... could you point me in the right direction please?

**Comment by vaaleyard** [comment]
Thanks for the contrib, @yusufsheiqh 
Really appreciate it.

**Pull request closed without merging**
